name = "ToolipsCrawl"
uuid = "bc5540b7-af16-444d-8eba-940cc7c9cf32"
authors = ["emmac <emmacboudreau@gmail.com>"]
version = "0.2.0"

[deps]
Toolips = "a47e2ad8-fcf7-417c-9746-32b9bdf220bd"

[compat]
julia = "1.5"
Toolips = "0.3.10"
